# -*- coding: utf-8 -*-
"""dados_keywords.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OJ_tW5l0q9o_0Lpeq_7zTLAhL0q-6f-a
"""

import json
from collections import Counter
import pandas as pd

from google.colab import files

arquivo = files.upload()

nome = list(arquivo.keys())[0]
conteudo = arquivo[nome]

print(conteudo)

conteudo_decode = conteudo.decode('utf-8')
dados_json = json.loads(conteudo_decode)

print(dados_json)

all_keywords = [keyword for keywords_list in dados_json.values() for keyword in keywords_list]
keyword_counts = Counter(all_keywords)
df_keywords = pd.DataFrame(keyword_counts.items(), columns=['Palavra-chave', 'Contagem'])
df_keywords_sorted = df_keywords.sort_values(by='Contagem', ascending=False)

top_20_keywords = df_keywords_sorted.head(20)

print(top_20_keywords.to_string(index=False))